services:
  swifttask-frontend:
    build:
      context : .
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    networks:
      - swifttask-network

networks:
  swifttask-network:
    driver: bridge